<?xml version="1.0"?>
<!DOCTYPE feature_vector_file [
   <!ELEMENT feature_vector_file (comments, data_set+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT data_set (data_set_id, section*, feature*)>
   <!ELEMENT data_set_id (#PCDATA)>
   <!ELEMENT section (feature+)>
   <!ATTLIST section start CDATA ""
                     stop CDATA "">
   <!ELEMENT feature (name, v+)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT v (#PCDATA)>
]>

<feature_vector_file>

   <comments>Combined feature vectors of C:\Users\Cory\Documents\_ISMIR\Data\SLAC_Feature_Values\Lyrics\lyrics_feature_values.xml and C:\Users\Cory\Documents\_ISMIR\Data\SLAC_Feature_Values\Cultural\cultural_features_artist_10.xml.</comments>

   <data_set>
      <data_set_id>Born Under A Bad Sign</data_set_id>
      <feature>
         <name>Average syllable count per word</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh reading ease</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh-Kincaid grade level</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Letter-bigram components</name>
         <v>0.028006418382865824</v>
         <v>0.01824039400475522</v>
         <v>0.031447050140227806</v>
         <v>-0.02901888106742915</v>
         <v>-0.013206709251805723</v>
         <v>0.00960431276221881</v>
         <v>0.01304813073362782</v>
         <v>0.010874260219627532</v>
         <v>0.008839619167211567</v>
         <v>-0.023739800211889976</v>
         <v>-0.010070704877429452</v>
         <v>0.008911201227175368</v>
         <v>-0.015553260422642202</v>
         <v>-0.0052513795947831095</v>
         <v>0.015260173667739114</v>
         <v>0.003159783063408101</v>
         <v>-0.010007671441934554</v>
         <v>0.009473072514915542</v>
         <v>-0.006783178503979872</v>
         <v>0.003889201044639219</v>
      </feature>
      <feature>
         <name>Part-of-speech frequencies</name>
         <v>0.00892857142857</v>
         <v>0.00892857142857</v>
         <v>0.0803571428571</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.125</v>
         <v>0.09375</v>
         <v>0.0</v>
         <v>0.03125</v>
         <v>0.138392857143</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.142857142857</v>
         <v>0.09375</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.0267857142857</v>
         <v>0.00446428571429</v>
         <v>0.196428571429</v>
         <v>0.00446428571429</v>
      </feature>
      <feature>
         <name>Rate of misspelling</name>
         <v>0.0100502512563</v>
      </feature>
      <feature>
         <name>Topic membership probabilities (24 topics)</name>
         <v>0.00138747922010492</v>
         <v>0.00138683803399285</v>
         <v>0.00138687190146263</v>
         <v>0.00138714203474172</v>
         <v>0.00138664458904402</v>
         <v>0.00138698623324234</v>
         <v>0.00138710423768286</v>
         <v>0.922786725251223</v>
         <v>0.0466984611193034</v>
         <v>0.00138693632841648</v>
         <v>0.00138679714112847</v>
         <v>0.0013863280299894</v>
         <v>0.00138738451590261</v>
         <v>0.00138695024812508</v>
         <v>0.00138702493076905</v>
         <v>0.00138671733017759</v>
         <v>0.00138687361725368</v>
         <v>0.00138670894998429</v>
         <v>0.0013872360151029</v>
         <v>0.00138706509954695</v>
         <v>0.00138753479689929</v>
         <v>0.0013879880014011</v>
         <v>0.00138687606403823</v>
         <v>0.00138732631046674</v>
      </feature>
      <feature>
         <name>Contains Words</name>
         <v>1.0</v>
      </feature>
      <feature>
         <name>Number of Words</name>
         <v>199.0</v>
      </feature>
      <feature>
         <name>Number of Unique Words</name>
         <v>69.0</v>
      </feature>
      <feature>
         <name>Word Variety</name>
         <v>2.8840579710144927</v>
      </feature>
      <feature>
         <name>Letters Per Word Average</name>
         <v>3.492462311557789</v>
      </feature>
      <feature>
         <name>Letters Per Word Variance</name>
         <v>2.8572661286229106</v>
      </feature>
      <feature>
         <name>Number of Lines</name>
         <v>23.0</v>
      </feature>
      <feature>
         <name>Words Per Line Average</name>
         <v>8.652173913043478</v>
      </feature>
      <feature>
         <name>Words Per Line Variance</name>
         <v>10.328063241106719</v>
      </feature>
      <feature>
         <name>Number of Segments</name>
         <v>7.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Average</name>
         <v>3.2857142857142856</v>
      </feature>
      <feature>
         <name>Lines Per Segment Variance</name>
         <v>2.2380952380952386</v>
      </feature>
      <feature>
         <name>Automated Readability Index</name>
         <v>-0.6544155560410765</v>
      </feature>
      <feature>
         <name>Word Profile Match Traditional Blues</name>
         <v>1.5075376884422111</v>
      </feature>
      <feature>
         <name>Word Profile Match Modern Blues</name>
         <v>10.050251256281408</v>
      </feature>
      <feature>
         <name>Word Profile Match Classical</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Word Profile Match Jazz</name>
         <v>0.5025125628140703</v>
      </feature>
      <feature>
         <name>Word Profile Match Rap</name>
         <v>1.0050251256281406</v>
      </feature>
      <feature>
         <name>Word Profile Match Metal</name>
         <v>1.5075376884422111</v>
      </feature>
      <feature>
         <name>Country Blues_websearch</name>
         <v>0.24611317224363902</v>
      </feature>
      <feature>
         <name>Modern Blues_websearch</name>
         <v>0.6583186239988938</v>
      </feature>
      <feature>
         <name>Baroque Classical_websearch</name>
         <v>0.005616036013995705</v>
      </feature>
      <feature>
         <name>Romantic Classical_websearch</name>
         <v>0.0053619161081722745</v>
      </feature>
      <feature>
         <name>Bebop Jazz_websearch</name>
         <v>0.01702023214035627</v>
      </feature>
      <feature>
         <name>Swing Jazz_websearch</name>
         <v>0.020794794271819874</v>
      </feature>
      <feature>
         <name>Hardcore Rap_websearch</name>
         <v>0.0020717916320070165</v>
      </feature>
      <feature>
         <name>Pop Rap_websearch</name>
         <v>0.0025570218072720786</v>
      </feature>
      <feature>
         <name>Alternative Rock_websearch</name>
         <v>0.022400599484099393</v>
      </feature>
      <feature>
         <name>Metal_websearch</name>
         <v>0.019745812299744717</v>
      </feature>
      <feature>
         <name>Country Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Modern Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Baroque Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Romantic Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Bebop Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Swing Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Hardcore Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Pop Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Alternative Rock_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Metal_lastfm</name>
         <v>0.0</v>
      </feature>
   </data_set>

   <data_set>
      <data_set_id>How Blue Can You Get</data_set_id>
      <feature>
         <name>Average syllable count per word</name>
         <v>1.18</v>
      </feature>
      <feature>
         <name>Flesh reading ease</name>
         <v>47.67</v>
      </feature>
      <feature>
         <name>Flesh-Kincaid grade level</name>
         <v>21.14</v>
      </feature>
      <feature>
         <name>Letter-bigram components</name>
         <v>0.042496386896703556</v>
         <v>0.02562782566746157</v>
         <v>-5.763176736179835E-4</v>
         <v>0.004378185715722485</v>
         <v>0.008451059339280092</v>
         <v>0.011749350495046097</v>
         <v>1.143116832357632E-4</v>
         <v>0.0031276935902907295</v>
         <v>3.3319767047635865E-4</v>
         <v>-0.011335382320963093</v>
         <v>0.0033637552287102373</v>
         <v>0.016132690488615944</v>
         <v>-0.0015818808218495588</v>
         <v>-0.008537461132219638</v>
         <v>-0.003343465201147378</v>
         <v>6.916933386110583E-4</v>
         <v>0.0015263347085570664</v>
         <v>0.0096158584175775</v>
         <v>-0.011319712693325086</v>
         <v>0.009152364724347491</v>
      </feature>
      <feature>
         <name>Part-of-speech frequencies</name>
         <v>0.0391061452514</v>
         <v>0.00558659217877</v>
         <v>0.0614525139665</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.0446927374302</v>
         <v>0.0558659217877</v>
         <v>0.0</v>
         <v>0.0167597765363</v>
         <v>0.167597765363</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.223463687151</v>
         <v>0.072625698324</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.223463687151</v>
         <v>0.0391061452514</v>
      </feature>
      <feature>
         <name>Rate of misspelling</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Topic membership probabilities (24 topics)</name>
         <v>0.00200088776998673</v>
         <v>0.00199910771668415</v>
         <v>0.00199996194060098</v>
         <v>0.0735957170527286</v>
         <v>0.00199896683183917</v>
         <v>0.0020007514949003</v>
         <v>0.00200020753104465</v>
         <v>0.255419093971883</v>
         <v>0.00200069186136666</v>
         <v>0.00199997734326141</v>
         <v>0.0019999008423294</v>
         <v>0.00199906146915489</v>
         <v>0.00200106815105954</v>
         <v>0.00200124923726626</v>
         <v>0.458144130393009</v>
         <v>0.00199999604730746</v>
         <v>0.00199981534952938</v>
         <v>0.00200135755494975</v>
         <v>0.00200015787440339</v>
         <v>0.0314683624756303</v>
         <v>0.0020005751677709</v>
         <v>0.143368047561696</v>
         <v>0.00200040034515326</v>
         <v>0.00200051401644475</v>
      </feature>
      <feature>
         <name>Contains Words</name>
         <v>1.0</v>
      </feature>
      <feature>
         <name>Number of Words</name>
         <v>159.0</v>
      </feature>
      <feature>
         <name>Number of Unique Words</name>
         <v>75.0</v>
      </feature>
      <feature>
         <name>Word Variety</name>
         <v>2.12</v>
      </feature>
      <feature>
         <name>Letters Per Word Average</name>
         <v>3.7861635220125787</v>
      </feature>
      <feature>
         <name>Letters Per Word Variance</name>
         <v>2.194490884483721</v>
      </feature>
      <feature>
         <name>Number of Lines</name>
         <v>24.0</v>
      </feature>
      <feature>
         <name>Words Per Line Average</name>
         <v>6.625</v>
      </feature>
      <feature>
         <name>Words Per Line Variance</name>
         <v>1.1141304347826089</v>
      </feature>
      <feature>
         <name>Number of Segments</name>
         <v>3.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Average</name>
         <v>8.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Variance</name>
         <v>11.999999999999998</v>
      </feature>
      <feature>
         <name>Automated Readability Index</name>
         <v>-0.28466981132075375</v>
      </feature>
      <feature>
         <name>Word Profile Match Traditional Blues</name>
         <v>8.176100628930818</v>
      </feature>
      <feature>
         <name>Word Profile Match Modern Blues</name>
         <v>10.062893081761006</v>
      </feature>
      <feature>
         <name>Word Profile Match Classical</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Word Profile Match Jazz</name>
         <v>8.176100628930818</v>
      </feature>
      <feature>
         <name>Word Profile Match Rap</name>
         <v>0.6289308176100629</v>
      </feature>
      <feature>
         <name>Word Profile Match Metal</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Country Blues_websearch</name>
         <v>0.23528662246871387</v>
      </feature>
      <feature>
         <name>Modern Blues_websearch</name>
         <v>0.5169111574885935</v>
      </feature>
      <feature>
         <name>Baroque Classical_websearch</name>
         <v>0.012305285963904409</v>
      </feature>
      <feature>
         <name>Romantic Classical_websearch</name>
         <v>0.015455333677070984</v>
      </feature>
      <feature>
         <name>Bebop Jazz_websearch</name>
         <v>0.020051089969099798</v>
      </feature>
      <feature>
         <name>Swing Jazz_websearch</name>
         <v>0.06862372523037485</v>
      </feature>
      <feature>
         <name>Hardcore Rap_websearch</name>
         <v>0.0044149411941940345</v>
      </feature>
      <feature>
         <name>Pop Rap_websearch</name>
         <v>0.050107162868290686</v>
      </feature>
      <feature>
         <name>Alternative Rock_websearch</name>
         <v>0.038544152374069725</v>
      </feature>
      <feature>
         <name>Metal_websearch</name>
         <v>0.038300528765688034</v>
      </feature>
      <feature>
         <name>Country Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Modern Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Baroque Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Romantic Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Bebop Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Swing Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Hardcore Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Pop Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Alternative Rock_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Metal_lastfm</name>
         <v>0.0</v>
      </feature>
   </data_set>

   <data_set>
      <data_set_id>Rock Me Baby</data_set_id>
      <feature>
         <name>Average syllable count per word</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh reading ease</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh-Kincaid grade level</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Letter-bigram components</name>
         <v>0.031896732980167965</v>
         <v>0.029253682312632062</v>
         <v>0.04579712391258658</v>
         <v>0.04593828957139083</v>
         <v>-0.025520254759549357</v>
         <v>0.003591113830898363</v>
         <v>-0.019946227795365975</v>
         <v>0.02541186045240419</v>
         <v>-0.0244395169013682</v>
         <v>0.004673584016959183</v>
         <v>-0.01776578915014998</v>
         <v>-0.022849919953156574</v>
         <v>-0.016185705218686976</v>
         <v>-0.007450454427114917</v>
         <v>0.005614444434311811</v>
         <v>0.023593940180248945</v>
         <v>-0.025532956831231933</v>
         <v>0.004339007324909508</v>
         <v>0.00863978373506399</v>
         <v>-0.014760879614967389</v>
      </feature>
      <feature>
         <name>Part-of-speech frequencies</name>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.037037037037</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.037037037037</v>
         <v>0.0277777777778</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.212962962963</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.240740740741</v>
         <v>0.0740740740741</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.037037037037</v>
         <v>0.00925925925926</v>
         <v>0.203703703704</v>
         <v>0.00925925925926</v>
      </feature>
      <feature>
         <name>Rate of misspelling</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Topic membership probabilities (24 topics)</name>
         <v>0.0025678191261052</v>
         <v>0.00256608678152237</v>
         <v>0.00256634638505413</v>
         <v>0.00256793462926215</v>
         <v>0.00256608678152237</v>
         <v>0.00256794565375772</v>
         <v>0.00256827345752379</v>
         <v>0.00256898078787697</v>
         <v>0.00256819556088444</v>
         <v>0.525906996831501</v>
         <v>0.00256608678152237</v>
         <v>0.00256633577025003</v>
         <v>0.00256765683845203</v>
         <v>0.00256737132722103</v>
         <v>0.417606918158563</v>
         <v>0.00256828312948696</v>
         <v>0.00256790842795575</v>
         <v>0.00256839882204359</v>
         <v>0.00256832933662553</v>
         <v>0.00256791135816688</v>
         <v>0.00256821578566566</v>
         <v>0.0025670662503782</v>
         <v>0.00256792729278597</v>
         <v>0.00256692472587337</v>
      </feature>
      <feature>
         <name>Contains Words</name>
         <v>1.0</v>
      </feature>
      <feature>
         <name>Number of Words</name>
         <v>94.0</v>
      </feature>
      <feature>
         <name>Number of Unique Words</name>
         <v>37.0</v>
      </feature>
      <feature>
         <name>Word Variety</name>
         <v>2.5405405405405403</v>
      </feature>
      <feature>
         <name>Letters Per Word Average</name>
         <v>3.5319148936170213</v>
      </feature>
      <feature>
         <name>Letters Per Word Variance</name>
         <v>1.6710134980553641</v>
      </feature>
      <feature>
         <name>Number of Lines</name>
         <v>12.0</v>
      </feature>
      <feature>
         <name>Words Per Line Average</name>
         <v>7.833333333333333</v>
      </feature>
      <feature>
         <name>Words Per Line Variance</name>
         <v>4.333333333333333</v>
      </feature>
      <feature>
         <name>Number of Segments</name>
         <v>3.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Average</name>
         <v>4.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Variance</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Automated Readability Index</name>
         <v>-0.8780141843971627</v>
      </feature>
      <feature>
         <name>Word Profile Match Traditional Blues</name>
         <v>11.702127659574469</v>
      </feature>
      <feature>
         <name>Word Profile Match Modern Blues</name>
         <v>13.829787234042554</v>
      </feature>
      <feature>
         <name>Word Profile Match Classical</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Word Profile Match Jazz</name>
         <v>2.127659574468085</v>
      </feature>
      <feature>
         <name>Word Profile Match Rap</name>
         <v>4.25531914893617</v>
      </feature>
      <feature>
         <name>Word Profile Match Metal</name>
         <v>3.1914893617021276</v>
      </feature>
      <feature>
         <name>Country Blues_websearch</name>
         <v>0.23445799837472986</v>
      </feature>
      <feature>
         <name>Modern Blues_websearch</name>
         <v>0.5184010697399494</v>
      </feature>
      <feature>
         <name>Baroque Classical_websearch</name>
         <v>0.01247336256849654</v>
      </feature>
      <feature>
         <name>Romantic Classical_websearch</name>
         <v>0.015400903630300746</v>
      </feature>
      <feature>
         <name>Bebop Jazz_websearch</name>
         <v>0.01998047475058585</v>
      </feature>
      <feature>
         <name>Swing Jazz_websearch</name>
         <v>0.06838204862526999</v>
      </feature>
      <feature>
         <name>Hardcore Rap_websearch</name>
         <v>0.004399392810658042</v>
      </feature>
      <feature>
         <name>Pop Rap_websearch</name>
         <v>0.049930697236720965</v>
      </feature>
      <feature>
         <name>Alternative Rock_websearch</name>
         <v>0.03840840894333731</v>
      </feature>
      <feature>
         <name>Metal_websearch</name>
         <v>0.03816564331995132</v>
      </feature>
      <feature>
         <name>Country Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Modern Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Baroque Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Romantic Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Bebop Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Swing Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Hardcore Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Pop Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Alternative Rock_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Metal_lastfm</name>
         <v>0.0</v>
      </feature>
   </data_set>

   <data_set>
      <data_set_id>The Thrill Is Gone</data_set_id>
      <feature>
         <name>Average syllable count per word</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh reading ease</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh-Kincaid grade level</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Letter-bigram components</name>
         <v>0.04418714226798624</v>
         <v>-0.010724666885904814</v>
         <v>0.014902715086677253</v>
         <v>0.02750714515680452</v>
         <v>-0.005440323062340536</v>
         <v>0.01258547748547456</v>
         <v>0.01872667859648404</v>
         <v>2.2943801955576507E-4</v>
         <v>-0.011064683706336927</v>
         <v>0.021014169101256558</v>
         <v>-0.0032201659350640376</v>
         <v>-0.01707251802551565</v>
         <v>0.012962765022477259</v>
         <v>0.014332434952568477</v>
         <v>-0.0029771338832996256</v>
         <v>0.0153844010560202</v>
         <v>0.019391673018883657</v>
         <v>0.022466608784252634</v>
         <v>0.014218079964199803</v>
         <v>0.009312637730196551</v>
      </feature>
      <feature>
         <name>Part-of-speech frequencies</name>
         <v>0.0258064516129</v>
         <v>0.0</v>
         <v>0.0774193548387</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.0709677419355</v>
         <v>0.0967741935484</v>
         <v>0.0</v>
         <v>0.0387096774194</v>
         <v>0.148387096774</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.154838709677</v>
         <v>0.0903225806452</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.0</v>
         <v>0.00645161290323</v>
         <v>0.264516129032</v>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Rate of misspelling</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Topic membership probabilities (24 topics)</name>
         <v>0.00214658811997631</v>
         <v>0.00214481827320197</v>
         <v>0.00214489020452115</v>
         <v>0.00214557605225178</v>
         <v>0.00214481827320197</v>
         <v>0.00214522759913437</v>
         <v>0.00214531796404432</v>
         <v>0.00214622890053995</v>
         <v>0.00214571021893347</v>
         <v>0.00214516273866058</v>
         <v>0.00214481827320197</v>
         <v>0.00214494535246054</v>
         <v>0.00214550969856083</v>
         <v>0.00214519827599309</v>
         <v>0.721548216794894</v>
         <v>0.00214511341792876</v>
         <v>0.00214531965482562</v>
         <v>0.00214611414406013</v>
         <v>0.23125201668367</v>
         <v>0.00214534085204379</v>
         <v>0.0021454709073113</v>
         <v>0.00214723828888326</v>
         <v>0.00214516931247027</v>
         <v>0.0021451899992303</v>
      </feature>
      <feature>
         <name>Contains Words</name>
         <v>1.0</v>
      </feature>
      <feature>
         <name>Number of Words</name>
         <v>139.0</v>
      </feature>
      <feature>
         <name>Number of Unique Words</name>
         <v>59.0</v>
      </feature>
      <feature>
         <name>Word Variety</name>
         <v>2.3559322033898304</v>
      </feature>
      <feature>
         <name>Letters Per Word Average</name>
         <v>3.762589928057554</v>
      </feature>
      <feature>
         <name>Letters Per Word Variance</name>
         <v>1.8635178813471</v>
      </feature>
      <feature>
         <name>Number of Lines</name>
         <v>25.0</v>
      </feature>
      <feature>
         <name>Words Per Line Average</name>
         <v>5.56</v>
      </feature>
      <feature>
         <name>Words Per Line Variance</name>
         <v>1.5066666666666666</v>
      </feature>
      <feature>
         <name>Number of Segments</name>
         <v>5.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Average</name>
         <v>5.0</v>
      </feature>
      <feature>
         <name>Lines Per Segment Variance</name>
         <v>5.000000000000001</v>
      </feature>
      <feature>
         <name>Automated Readability Index</name>
         <v>-0.9282014388489195</v>
      </feature>
      <feature>
         <name>Word Profile Match Traditional Blues</name>
         <v>5.0359712230215825</v>
      </feature>
      <feature>
         <name>Word Profile Match Modern Blues</name>
         <v>5.0359712230215825</v>
      </feature>
      <feature>
         <name>Word Profile Match Classical</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Word Profile Match Jazz</name>
         <v>6.474820143884892</v>
      </feature>
      <feature>
         <name>Word Profile Match Rap</name>
         <v>0.7194244604316546</v>
      </feature>
      <feature>
         <name>Word Profile Match Metal</name>
         <v>0.7194244604316546</v>
      </feature>
      <feature>
         <name>Country Blues_websearch</name>
         <v>0.23467059695954345</v>
      </feature>
      <feature>
         <name>Modern Blues_websearch</name>
         <v>0.5188711383004445</v>
      </feature>
      <feature>
         <name>Baroque Classical_websearch</name>
         <v>0.012484672991891398</v>
      </feature>
      <feature>
         <name>Romantic Classical_websearch</name>
         <v>0.015414868648936703</v>
      </feature>
      <feature>
         <name>Bebop Jazz_websearch</name>
         <v>0.019998592369457134</v>
      </feature>
      <feature>
         <name>Swing Jazz_websearch</name>
         <v>0.06844405515464909</v>
      </feature>
      <feature>
         <name>Hardcore Rap_websearch</name>
         <v>0.004403382031294867</v>
      </feature>
      <feature>
         <name>Pop Rap_websearch</name>
         <v>0.049709434183495584</v>
      </feature>
      <feature>
         <name>Alternative Rock_websearch</name>
         <v>0.03844323638980064</v>
      </feature>
      <feature>
         <name>Metal_websearch</name>
         <v>0.03756002297048674</v>
      </feature>
      <feature>
         <name>Country Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Modern Blues_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Baroque Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Romantic Classical_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Bebop Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Swing Jazz_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Hardcore Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Pop Rap_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Alternative Rock_lastfm</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Metal_lastfm</name>
         <v>0.0</v>
      </feature>
   </data_set>

   <data_set>
      <data_set_id>Don't Answer the Door</data_set_id>
      <feature>
         <name>Average syllable count per word</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh reading ease</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Flesh-Kincaid grade level</name>
         <v>0.0</v>
      </feature>
      <feature>
         <name>Letter-bigram components</name>
         <v>-0.06068805385581976</v>
         <v>-2.566515952047371E-4</v>
         <v>-7.859592339562734E-4</v>
         <v>0.0014168297884494137</v>
         <v>-6.792987652087288E-5</v>
         <v>4.5726950217885395E-4</v>
         <v>3.351373017215964E-4</v>
         <v>-1.866015972418492E-5</v>
         <v>2.1213182626605664E-4</v>
         <v>-4.400152575393546E-4</v>
         <v>-1.2437942709250297E-4</v>
         <v>2.0822854051637444E-5</v>
         <v>1.0013801172232113E-4</v>
         <v>1.2390083504713957E-4</v>
         <v>1.8042469352308613E-5</v>
         <v>-3.651578377715112E-4</v>
         <v>-1.6942774121506986E-4</v>
         <v>-6.391909906226476E-5</v>
         <v>7.758186601217869E-5</v>
         <v>1.8696572352689367E-5</v>
      </feature>
      <feature>
         <name>Part-of-speech frequencies</name>