<?xml version="1.0"?>
<!DOCTYPE classifications_file [
   <!ELEMENT classifications_file (comments, data_set+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT data_set (data_set_id, misc_info*, role?, classification)>
   <!ELEMENT data_set_id (#PCDATA)>
   <!ELEMENT misc_info (#PCDATA)>
   <!ATTLIST misc_info info_type CDATA "">
   <!ELEMENT role (#PCDATA)>
   <!ELEMENT classification (section*, class*)>
   <!ELEMENT section (start, stop, class+)>
   <!ELEMENT class (#PCDATA)>
   <!ELEMENT start (#PCDATA)>
   <!ELEMENT stop (#PCDATA)>
]>

<classifications_file>

   <comments></comments>

   <data_set>
      <data_set_id>Albert_King___Born_Under_A_Bad_Sign</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>B_B__King___How_Blue_Can_You_Get</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>B_B__King___Rock_Me_Baby</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>B_B__King___The_Thrill_Is_Gone</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Buddy_Guy___Don_t_Answer_the_Door</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Cream___Crossroads</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Derek_and_the_Dominoes___Key_to_the_Highway</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Derek_and_the_Dominoes___Nobody_Knows_You_When_You_re_Down_and_Out</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Gary_Moore___Still_Got_The_Blues</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>James_Cotton___Sweet_Sixteen</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johnny_Winter___Good_Morning_Little_Schoolgirl</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johnny_Winter___Unseen_Eye</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Koko_Taylor___Let_the_Good_Times_Roll</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Led_Zeppelin___I_Can_t_Quit_You_Baby</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Led_Zeppelin___Since_I_ve_Been_Loving_You</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Stevie_Ray_Vaughan___Cold_Shot</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Stevie_Ray_Vaughan___Honey_Bee</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Stevie_Ray_Vaughan___Pride_And_Joy</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Stevie_Ray_Vaughan___Texas_Flood</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ten_Years_After___Help_Me</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>The_Allman_Brothers_Band___It_s_Not_My_Cross_To_Bear</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>The_Allman_Brothers_Band___One_Way_Out</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>The_Allman_Brothers_Band___Statesboro_Blues</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>The_Allman_Brothers_Band___Stormy_Monday</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>The_Doors___Roadhouse_Blues</data_set_id>
      <classification>
         <class>Blues - Modern</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Blind_Lemon_Jefferson___Matchbox_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Brownie_McGhee___Ain_t_No_Tellin_</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Brownie_McGhee___Keys_to_the_Highway</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Buddy_Guy___Rollin__and_Tumblin_</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Charlie_Patton___Screamin__And_Hollerin__The_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Chris_Thomas_King___Hard_Time_Killing_Floor_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Doc_Watson___Blues_Stay_Away_From_Me</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Eric_Clapton___Before_You_Accuse_Me</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Howlin__Wolf___The_Red_Rooster</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>James_Cotton___Don_t_Start_Me_Talkin_</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>James_Cotton___Juke</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johnny_Winter___Dallas</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Lightnin__Hopkins___In_The_Evening_The_Sun_Is_Going_Down_Time</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Lightnin__Hopkins___Trouble_In_Mind_Time</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Mama_Yancey___How_Long_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Mississippi_Fred_McDowell___My_Babe</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Muddy_Waters___Good_Morning_Little_School_Girl</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Muddy_Waters___I_m_Your_Hoochie_Coochie_Man</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Muddy_Waters___Kansas_City</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Robert_Johnson___Cross_Road_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Robert_Johnson___I_Believe_I_ll_Dust_My_Broom</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Robert_Johnson___Sweet_Home_Chicago</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Robert_Johnson___Terraplane_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Robert_Johnson___Walking_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Skip_James___Special_Rider_Blues</data_set_id>
      <classification>
         <class>Blues - Traditional</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johann_Sebastian_Bach___The_Art_of_Fugue___Fuga_3</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johann_Sebastian_Bach___Cello_Suite_No__1__Prelude</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johann_Sebastian_Bach___Preludeand_Fugue__BWV_545__C_Major__1__Prelude</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johann_Sebastian_Bach___St__Matthew_Passion___Kommt__ihr_Tochter__helft_mir_klagen_</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johann_Sebastian_Bach___Was_bist_du_doch__o_Seele__so_betrubet</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Dietrich_Buxtehude___Fuga_C_dur</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Dietrich_Buxtehude___Herr_Jesu_Christ__ich_weiss_gar_wohl</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Dietrich_Buxtehude___Praeludium_In_E_Major__BuxWV_141___1</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Arcangelo_Corelli___Op_6_Concerto_No__8__Christmas__I_Vivace___Grave</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>George_Frideric_Handel___Solomon__The_Arrival_Of_The_Queen_Of_Sheba</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>George_Frideric_Handel___Suite_For_Harpsichord_In_D_Minor__Sarabande</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>George_Frideric_Handel___Water_Music__Suite_in_F_Major___Bourr_e</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Marin_Marais___Sonnerie_de_Ste__Genevieve_du_Mont_de_Paris</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Claudio_Monteverdi___Altri_Canti_d_Amor</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Claudio_Monteverdi___Ecco_pur_ch_a_voi_ritorno</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Claudio_Monteverdi___L_Orfeo__Tu_sei_morta</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johann_Pachelbel___Canon_In_D_Major</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Henry_Purcell___Dido_and_Aeneas__Act_3_Thy_hand_Belinda___When_I_am_laid_in_earth</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Domenico_Scarlatti___Keyboard_Sonata__K__1_In_D_Minor__Allegro</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Domenico_Scarlatti___Sonata_in_A_major__K39</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Domenico_Scarlatti___Sonata_In_D_Major__K__119___1</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Antonio_Vivaldi___Concerto_for_2_Violins__Cello_and_Orchestra_in_D_Minor___L_estro_armonico___Op__3__No__11__RV_565__1711___2__Largo_e_spiccato</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Antonio_Vivaldi____The_Four_Seasons___Spring___Concerto_in_E_major__Op__8_No__1___I__Allegro</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Antonio_Vivaldi___Concerto_no__6_in_A_minor_RV_356__I__Allegro_</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Antonio_Vivaldi___Concerto_no__3_in_G_major_RV_310__I__Allegro_</data_set_id>
      <classification>
         <class>Classical - Baroque</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ludwig_van_Beethoven___6_Bagatelles__Op__126</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ludwig_van_Beethoven___Symphony_No_3_in_E_flat_Major__Op__55__Eroica___I__Allegro_Con_Brio</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ludwig_van_Beethoven___Fur_Elise</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Hector_Berlioz___Harold_en_Italie_Op__16___1__Harold_aux_montagnes</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Hector_Berlioz___Symphony_Fantastique__Op__14___5__Songue_D_une_Nuit_Du_Sabbat</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Johannes_Brahms___Symphony_No__2_in_D_Op__73__Allegro_Non_Troppo</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Fryderyk_Chopin___Ballade_No__3_in_A_flat_major__Op__47</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Fryderyk_Chopin___Nocturne_no_13_in_c__Op_48_no_1</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Antonin_Dvorak___Symphonie_Nr__9___Adagio___Allegro_molto</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Franz_Liszt___Piano_Concerto_No__1_in_E_flat_major</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Franz_Liszt___Transcendental_Etudes__S_139___05__Feux_Follets</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Felix_Mendelssohn___A_Midsummer_Night_s_Dream___I_Overture</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Felix_Mendelssohn___Songs_Without_Words_Op_38_No_1</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Felix_Mendelssohn___Violin_Concerto_in_E_Minor__Op__64___II__Andante</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Niccolo_Paganini___Caprice__07_In_A_Minor</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Giacomo_Puccini___O_mio_babbino_caro</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Gioachino_Rossini___Una_voce_poco_fa</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Franz_Schubert___Gretchen_am_Spinnrade__Gretchen_at_the_Spinning_Wheel_</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Robert_Schumann___Piano_Trio_n__3_in_G__Op__110___1___Bewegt__Doch_Nicht_Zu_Rasch</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Giuseppe_Verdi___Aida___Romanza____Se_quel_guerrier_io_fossi______Celeste_Aida_</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Giuseppe_Verdi___Aida___Gran_finale_II___Gloria_all_Egitto__ad_Iside_</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Giuseppe_Verdi___Requiem__Libera_me__Dies_irae</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Richard_Wagner___Ride_of_the_Valkyries</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Richard_Wagner___Siegfired___Idyll</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Richard_Wagner___Tristan_und_Isolde__Prelude___1</data_set_id>
      <classification>
         <class>Classical - Romantic</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Art_Blakey___Moanin_</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Bud_Powell___Ornithology</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Bud_Powell___Scrapple_From_the_Apple</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Charlie_Parker___Au_Privave</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Charlie_Parker___Donna_Lee</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Dizzy_Gillespie___52nd_Street_Theme</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Dizzy_Gillespie___Groovin__High</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Herbie_Hancock___Cantaloupe_Island</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Herbie_Hancock___Watermelon_Man</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Horace_Silver___Opus_De_Funk</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>J__J__Johnson___Softly__As_In_The_Morning_Sunrise</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Jimmy_Smith___Back_At_The_Chicken_Shack</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>John_Coltrane___Airegin</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>John_Coltrane___Lazy_Bird</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>John_Coltrane___Mr__P_C_</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Lee_Morgan___The_Sidewinder</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Max_Roach___Billie_s_Bounce</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Miles_Davis___Blue__n__Boogie</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Miles_Davis___Doxy</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Miles_Davis___Half_Nelson</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Miles_Davis___Well__You_Needn_t</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Thelonious_Monk___Evidence</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Thelonious_Monk___In_Walked_Bud</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Thelonious_Monk___Straight_No_Chaser</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Wes_Montgomery___Four_On_Six</data_set_id>
      <classification>
         <class>Jazz - Bop</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Art_Tatum___In_A_Sentimental_Mood</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ben_Webster___Bye_Bye_Blackbird</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Benny_Goodman___Sing__Sing__Sing</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Billie_Holiday___Darn_That_Dream</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Billie_Holiday___Do_Nothing_til_You_Hear_From_Me</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Billie_Holiday___It_Had_To_Be_You</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Billie_Holiday___Prelude_To_A_Kiss</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Billie_Holiday___Sophisticated_Lady</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Chick_Webb___Don_t_Be_That_Way_</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Count_Basie___April_In_Paris</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Count_Basie___Autumn_Leaves</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Count_Basie___Corner_Pocket</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Count_Basie___Freckle_Face</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Duke_Ellington___Cottontail</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Duke_Ellington___Don_t_Get_Around_Much_Anymore</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Duke_Ellington___It_Don_t_Mean_A_Thing</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Duke_Ellington___Perdido</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Duke_Ellington___Stompin__at_the_Savoy</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Duke_Ellington___Take_The_A_Train</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ella_Fitzgerald___A_Foggy_Day</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ella_Fitzgerald___Don_t_Be_That_Way</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Ella_Fitzgerald___Satin_Doll</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Louis_Armstrong___I_ve_Got_The_World_On_A_String</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Sarah_Vaughan___If_I_Were_A_Bell</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>The_Dorsey_Brothers___St__Louis_Blues</data_set_id>
      <classification>
         <class>Jazz - Swing</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Bone_Thugs_N_Harmony___1st_of_tha_Month</data_set_id>
      <classification>
         <class>Rap - Hardcore Rap</class>
      </classification>
   </data_set>

   <data_set>
      <data_set_id>Bone_Thugs_N_Harmony___Look_into_My_Eyes</data_set_id>
      <classification>
         <class>Rap - Hardcore Rap</class>